import type {
  AdminSiteConfig,
  ThemeTokens,
  ManufacturerConfig,
  AboutPageConfig,
  CartConfig,
  CheckoutPaymentConfig,
} from './types';
import { categories, allProducts, epicDeals, brandLogosList } from '../data/products';

export const defaultThemeTokens: ThemeTokens = {
  colorPrimary: '#7C3AED',
  colorPrimaryHover: '#6D28D9',
  colorSecondary: '#15803D',
  colorSecondaryHover: '#166534',
  colorAccent: '#EA580C',
  colorBackground: '#F8FAFC',
  colorSurface: '#FFFFFF',
  colorTextPrimary: '#0F172A',
  colorTextMuted: '#64748B',
  colorBorder: '#E2E8F0',

  headerBackground: '#FFFFFF',
  headerTextColor: '#0F172A',
  headerSearchBorder: '#E2E8F0',
  headerSearchFocus: '#8B5CF6',
  navbarBackground: '#EDE9FE',
  navbarBorderColor: '#DDD6FE',
  navbarTextColor: '#5B21B6',
  navbarActiveColor: '#6D28D9',
  navbarCategoriesBtnBg: '#DCFCE7',
  navbarCategoriesBtnText: '#15803D',

  heroBackground: '#F3E8FF',
  heroBorderColor: '#EDE9FE',

  btnPrimaryBg: '#7C3AED',
  btnPrimaryText: '#FFFFFF',
  btnPrimaryHoverBg: '#6D28D9',
  btnSecondaryBg: '#DCFCE7',
  btnSecondaryText: '#15803D',
  btnAccentBg: '#EA580C',
  btnAccentText: '#FFFFFF',

  cardBg: '#FFFFFF',
  cardBorder: '#F1F5F9',
  cardShadow: '0 4px 18px rgba(0, 0, 0, 0.06)',
  cardPriceColor: '#7C3AED',

  dealsBannerBgStart: '#4C1D95',
  dealsBannerBgMiddle: '#5B21B6',
  dealsBannerBgEnd: '#3B0764',
  dealsNeonBadgeBg: '#0F172A',
  dealsNeonBadgeBorder: '#FACC15',
  dealsNeonBadgeText: '#FDE047',

  footerBg: '#0F172A',
  footerTextColor: '#94A3B8',
  footerHeadingColor: '#FFFFFF',
  footerLinkColor: '#CBD5E1',
  footerLinkHover: '#C4B5FD',
  footerBorderColor: '#1E293B',

  statusSuccess: '#16A34A',
  statusWarning: '#D97706',
  statusError: '#DC2626',
  statusInfo: '#2563EB',
};

export const defaultManufacturerConfig: ManufacturerConfig = {
  enabled: true,
  comingSoonMode: true,
  comingSoonBadge: 'Coming Soon',
  comingSoonTitle: 'Manufacturer',
  comingSoonText:
    "We're working on something exciting. This page will be available soon with all the details you need.",
  companyName: 'Farminix Private Limited',
  pageTitle: 'Official Manufacturing & Processing Hub',
  tagline: 'Pure Grains. Direct From Soil to Soul.',
  aboutCorporate:
    'Farminix bridges generational Andhra paddy farmers and your dining table. Zero middlemen, zero chemical polishing, and zero stale godowns — just honest, farm-fresh rice processed through cutting-edge optical Sortex technology and packed right at the source.',
  cinOrRegNumber: 'U01100AP2024PTC123456',
  fssaiNumber: '20126142000933',
  registeredOffice: 'Flat No 302, Srinivasa Towers, Gorantla, Guntur – 522034, Andhra Pradesh',
  facilityHeadline: 'Processing & Milling Facilities',
  facilitySubheadline: 'Clean room optical Sortex cleaning and packaging centers across Andhra Pradesh',
  facilities: [
    {
      id: 'fac-1',
      name: 'Farminix Central Milling & Sortex Facility',
      location: 'Gorantla, Guntur District, Andhra Pradesh – 522034',
      type: 'Multi-Stage Optical Sortex Milling & Sealed Packaging Plant',
      capacity: '150 Metric Tons / Day',
      status: 'Active & Operational',
      fssaiNumber: '20126142000933',
      enabled: true,
    },
    {
      id: 'fac-2',
      name: 'Krishna-Godavari Direct Aggregation Hub',
      location: 'Tenali & Amaravati Basin, Andhra Pradesh',
      type: 'Direct Grower Paddy Procurement & Moisture Testing Center',
      capacity: '300 Metric Tons Buffer Storage',
      status: 'Active & Operational',
      fssaiNumber: '20126142000933',
      enabled: true,
    },
  ],
  processTitle: 'From Soil to Dining Table',
  processSubtitle: 'How Farminix Reinvents What You Eat',
  processSteps: [
    {
      id: 'step-1',
      step: '01',
      title: 'Sown in Guntur',
      desc: 'Cultivated by trusted generational farming families in the nutrient-dense Krishna-Godavari river basin.',
      enabled: true,
    },
    {
      id: 'step-2',
      step: '02',
      title: 'Sortex Cleaned',
      desc: 'Optical sensor cameras screen each grain, separating dust, stones, and broken pieces without chemical polish.',
      enabled: true,
    },
    {
      id: 'step-3',
      step: '03',
      title: 'Naturally Aged',
      desc: 'Controlled resting optimizes starch retrogradation for maximum fluffiness and zero stickiness when boiled.',
      enabled: true,
    },
    {
      id: 'step-4',
      step: '04',
      title: 'Delivered Direct',
      desc: 'Sealed in heavy-duty 26 Kg moisture-lock sacks and delivered directly to your doorstep by express logistics.',
      enabled: true,
    },
  ],
  certificationsTitle: 'Our Operating Philosophy & Standards',
  certificationsSubtitle: 'Built on Dignity, Health, Net Weight & Transparency',
  certifications: [
    {
      id: 'cert-1',
      title: 'Direct Farmer Dignity',
      authority: 'Ethical Sourcing Guarantee',
      number: 'Fair Trade Sourcing',
      status: '100% Verified',
      enabled: true,
    },
    {
      id: 'cert-2',
      title: 'Zero Synthetic Polish',
      authority: 'Pure Health Standard',
      number: 'Unadulterated Grains',
      status: 'Chemical-Free',
      enabled: true,
    },
    {
      id: 'cert-3',
      title: '26 Kg Moisture-Lock Bags',
      authority: 'Durable Packaging Standard',
      number: 'Certified Net Weight',
      status: 'Heavy-Duty Sealed',
      enabled: true,
    },
    {
      id: 'cert-4',
      title: 'Direct-to-Home Pricing',
      authority: 'Transparent Value',
      number: '₹1399 for 26 Kg (₹53.8/Kg)',
      status: 'Wholesale Direct',
      enabled: true,
    },
  ],
  b2bTitle: 'Corporate, Institutional & Wholesale Inquiries',
  b2bSubtitle: 'Partner directly with Farminix for bulk grain procurement and institutional supply',
  contactPhone: '+91 7989743595',
  contactEmail: 'info@farminix.in',
  supportHours: 'Monday – Saturday: 8:00 AM – 8:00 PM IST',
};

export const defaultAboutPageConfig: AboutPageConfig = {
  headline: 'Pure Grains. Direct From Soil to Soul.',
  subheadline:
    'Farminix bridges generational Andhra paddy farmers and your dining table. Zero middlemen, zero chemical polishing, and zero stale godowns — just honest, farm-fresh rice delivered in minutes.',
  tags: [
    '100% Single-Origin Paddy',
    'Naturally Aged for Fluffy Cook',
    'FSSAI Lic. 20126142000933',
  ],
  founderTitle: "Founder's Reflection",
  founderSubtitle: 'A Note from the Heart of Farminix • With Love to Every Household',
  founderLetter: `Dear Farminix Family,\n\nWhen you gather around the dinner table after a long day, a steaming bowl of rice is never just food. It is the comforting center of every family celebration, your grandmother’s timeless recipes, and the very feeling of coming home.\n\nWe started Farminix right here in Gorantla, Guntur with a deeply personal calling. We looked at standard grocery stores and saw rice that had spent 6 to 9 months inside dusty godowns, traded through five layers of commission middlemen, and subjected to harsh chemical polishes just to appear artificially white. Meanwhile, the generational farmers who woke up at dawn to tend the fertile Andhra soils were paid fractions of what families were charged.`,
  founderQuote:
    '“Why should Indian families settle for chemically polished, stale grains when our villages harvest the most fragrant, wholesome paddy in the world?”',
  founderSignoff: `Farminix is our answer. We partner directly with verified grower families across Andhra Pradesh, mill through cutting-edge optical Sortex technology, and pack our hallmark 26 Kg Family Choice bags right at the source. No middlemen inflating prices. No artificial bleaching. Just pure, whole, naturally aged grains that cook fluffy, fragrant, and healthy.\n\nEvery sack that reaches your doorstep carries the blessing of our soil, the dignity of our farmers, and our sacred promise of purity to your family.\n\nWith endless gratitude & love,\nThe Farminix Team`,
  companyAddress:
    'Farminix Private Limited • Flat No 302, Srinivasa Towers, Gorantla, Guntur – 522034, AP',
  processTitle: 'From Soil to Dining Table',
  processSubtitle: 'How Farminix Reinvents What You Eat',
  processSteps: [
    {
      step: '01',
      title: 'Sown in Guntur',
      desc: 'Cultivated by trusted generational farming families in the nutrient-dense Krishna-Godavari river basin.',
    },
    {
      step: '02',
      title: 'Sortex Cleaned',
      desc: 'Optical sensor cameras screen each grain, separating dust, stones, and broken pieces without chemical polish.',
    },
    {
      step: '03',
      title: 'Naturally Aged',
      desc: 'Controlled resting optimizes starch retrogradation for maximum fluffiness and zero stickiness when boiled.',
    },
    {
      step: '04',
      title: 'Delivered Direct',
      desc: 'Sealed in heavy-duty 26 Kg moisture-lock sacks and delivered directly to your doorstep by express logistics.',
    },
  ],
  philosophyTitle: 'Our Operating Philosophy',
  philosophySubtitle: 'Built on Dignity, Health & Transparency',
  philosophyPillars: [
    {
      tag: 'Ethical Sourcing',
      title: 'Direct Farmer Dignity',
      desc: 'By cutting out commission agents, we pay farmers fair, upfront prices for their harvest, strengthening rural livelihoods.',
      guarantee: 'Fair Trade Guarantee',
    },
    {
      tag: 'Pure Health',
      title: 'Zero Synthetic Polish',
      desc: 'We refuse chemical bleaches, powders, and adulterants. You receive the honest, natural nutrient richness of each grain.',
      guarantee: '100% Unadulterated',
    },
    {
      tag: 'Durable Packaging',
      title: '26 Kg Moisture-Lock Bags',
      desc: 'Heavy-duty multi-layer sacks engineered to seal in farm freshness and resist external humidity, pests, and transit damage.',
      guarantee: 'Certified Net Weight',
    },
    {
      tag: 'Transparent Value',
      title: 'Direct-to-Home Pricing',
      desc: 'Premium quality at ₹1399 for 26 Kg (₹53.8/Kg) — passing wholesale supply-chain efficiencies straight to your household.',
      guarantee: 'Honest Value',
    },
  ],
  calloutTitle: 'Taste True Purity in Every Single Grain.',
  calloutDesc:
    'Upgrade your family’s daily meals with the authentic taste and aroma of Farminix Family Choice Rice. Delivered directly to your door.',
  contactPhone: '+91 7989743595',
  contactEmail: 'info@farminix.in',
  contactLocation: 'Gorantla, Guntur – 522034, AP',
};

export const defaultCartConfig: CartConfig = {
  deliveryBannerText: 'Superfast Delivery! Your order will reach in 10 Mins.',
  deliveryTimeText: '10 Mins',
  handlingFee: 3,
  deliveryFee: 0,
  freeDeliveryThreshold: 0,
  coupons: [
    {
      code: 'FARM10',
      discountPercentage: 10,
      description: 'Coupon FARM10 active (10% OFF)',
      enabled: true,
    },
    {
      code: 'FARMINIX15',
      discountPercentage: 15,
      description: 'Special Festive 15% OFF',
      enabled: true,
    },
  ],
  emptyCartTitle: 'Your cart is empty',
  emptyCartSubtitle: 'Explore our wide range of fresh groceries and top brand products.',
  emptyCartButtonText: 'Start Shopping',
};

export const defaultCheckoutPaymentConfig: CheckoutPaymentConfig = {
  expressSlotLabel: '10-20 Min Express',
  expressSlotSublabel: 'Free Instant Doorstep Delivery',
  scheduledSlotLabel: 'Scheduled Slot',
  scheduledSlotSublabel: 'Today 6:00 PM - 8:00 PM',
  paymentMethods: [
    {
      id: 'razorpay',
      name: 'Razorpay Instant & Secure Pay (Recommended)',
      subtitle: 'Google Pay, PhonePe, Paytm, Cards, NetBanking & Wallets',
      icon: '⚡',
      enabled: true,
    },
    {
      id: 'upi',
      name: 'UPI / QR Payment',
      subtitle: 'Google Pay, PhonePe, BHIM, Paytm & Any UPI ID',
      icon: '📱',
      enabled: true,
      instruction: 'Pay seamlessly with Instant QR or UPI ID via Razorpay',
    },
    {
      id: 'card',
      name: 'Credit / Debit Card',
      subtitle: 'Visa, Mastercard, RuPay, Maestro & Corporate Cards',
      icon: '💳',
      enabled: true,
    },
    {
      id: 'netbanking',
      name: 'Net Banking',
      subtitle: 'HDFC, SBI, ICICI, Axis, Kotak & 50+ Banks',
      icon: '🏦',
      enabled: true,
    },
    {
      id: 'cod',
      name: 'Cash on Delivery (COD)',
      subtitle: 'Pay cash or UPI to delivery executive at doorstep',
      icon: '💵',
      enabled: true,
    },
  ],
  upiAutoVerifyText: '✓ Instant Auto-Verification via Razorpay',
  deliveryInstructions: [
    { id: 'door', label: 'Leave at Door', icon: '🚪', enabled: true },
    { id: 'bell', label: "Don't Ring Bell", icon: '🔕', enabled: true },
    { id: 'call', label: 'Call Before Delivery', icon: '📞', enabled: true },
    { id: 'security', label: 'Hand to Security', icon: '🛡️', enabled: true },
  ],
  safePaymentsBadgeText: '🔒 100% Safe Payments by Razorpay',
  razorpayKeyId: (import.meta as any).env?.VITE_RAZORPAY_KEY_ID || '',
  razorpayKeySecret: '',
  razorpayEnabled: true,
  razorpayMerchantName: 'Farminix Fresh Groceries',
  razorpayThemeColor: '#7C3AED',
};

export const defaultSiteConfig: AdminSiteConfig = {
  theme: defaultThemeTokens,
  manufacturer: defaultManufacturerConfig,
  aboutPage: defaultAboutPageConfig,
  cart: defaultCartConfig,
  checkoutPayment: defaultCheckoutPaymentConfig,
  sectionOrder: [
    { id: 'hero', name: 'Hero Banner', enabled: true, order: 1 },
    { id: 'brandMarquee', name: 'Trusted Brands Marquee', enabled: false, order: 2 },
    { id: 'featureStrip', name: 'Top 5 Feature Strip', enabled: false, order: 3 },
    { id: 'categorySection', name: 'Shop by Category', enabled: false, order: 4 },
    { id: 'popularProducts', name: 'Popular Today ⚡', enabled: true, order: 5 },
    { id: 'epicDeals', name: 'Epic Deals All Day', enabled: false, order: 6 },
    { id: 'futureArrivals', name: 'Future Arrivals', enabled: false, order: 7 },
    { id: 'bottomFeatureStrip', name: 'Bottom Benefits Strip', enabled: false, order: 8 },
  ],
  topOfferBar: {
    enabled: false,
    leftTextPrefix: '10% OFF on your first order | Use code: ',
    discountHighlight: '10% OFF',
    leftTextSuffix: ' on your first order | Use code:',
    promoCode: 'FARM10',
    downloadAppText: 'Download App',
    trackOrderText: 'Track Order',
    helpText: 'Help',
    appStoreAlertMessage: 'Farminix Mobile App available on iOS App Store & Google Play Store!',
  },
  header: {
    enabled: true,
    logoUrl: '/farminix_logo.png',
    logoAlt: 'Farminix Logo',
    deliveryLabel: 'Deliver to',
    searchPlaceholders: [
      'Search for rice, atta, oil, dal...',
      'Try "Daawat Basmati Rice"...',
      'Search for masala, spices...',
      'Try "Amul Butter"...',
      'Search for dals & pulses...',
      'Try "Aashirvaad Atta 5kg"...',
      'Search for snacks & beverages...',
      'Try "Fortune Sunflower Oil"...',
      'Search for household essentials...',
      'Try "Tata Salt 1kg"...',
    ],
    loginButtonText: 'Login / Sign up',
    cartButtonText: 'Cart',
  },
  navItems: [
    { id: 'nav-1', label: 'Home', catId: null, enabled: true, order: 1 },
    { id: 'nav-2', label: 'Dals & Pulses', catId: 'dals', enabled: true, order: 2 },
    { id: 'nav-3', label: 'Rice & Grains', catId: 'rice', enabled: true, order: 3 },
    { id: 'nav-4', label: 'Atta & Flours', catId: 'atta', enabled: true, order: 4 },
    { id: 'nav-5', label: 'Oils & Ghee', catId: 'oils', enabled: true, order: 5 },
    { id: 'nav-6', label: 'Masala & Spices', catId: 'masala', enabled: true, order: 6 },
    { id: 'nav-7', label: 'Snacks & Beverages', catId: 'snacks', enabled: true, order: 7 },
    { id: 'nav-8', label: 'Household', catId: 'household', enabled: true, order: 8 },
    { id: 'nav-9', label: 'Offers', catId: 'offers', badge: 'HOT', enabled: true, order: 9 },
    { id: 'nav-10', label: 'Manufacturer', catId: 'manufacturer', enabled: true, order: 10 },
  ],
  hero: {
    enabled: true,
    bannerImage: '/hero_banner_original.jpg',
    altText: 'Farminix Fresh Groceries',
    shopNowUrl: '/products',
    homeUrl: '/',
  },
  brandMarquee: {
    enabled: true,
    badgeText: 'Our Partners',
    title: 'Trusted Brands We Carry',
    description: "Authentic products from India's most loved brands — straight to your door.",
    brands: brandLogosList.map((b, idx) => ({
      id: `b-${idx + 1}`,
      name: b.name,
      logo: b.logo,
      enabled: true,
      order: idx + 1,
    })),
  },
  featureStrip: {
    enabled: true,
    features: [
      { id: 1, iconName: 'Zap', title: '10 Min Delivery', subtitle: 'Super Fast', bgColor: 'bg-purple-100', enabled: true, order: 1 },
      { id: 2, iconName: 'ShieldCheck', title: 'Quality Assured', subtitle: '100% Genuine', bgColor: 'bg-emerald-100', enabled: true, order: 2 },
      { id: 3, iconName: 'IndianRupee', title: 'Best Prices', subtitle: 'Direct from Brands', bgColor: 'bg-purple-100', enabled: true, order: 3 },
      { id: 4, iconName: 'Lock', title: 'Safe & Secure', subtitle: 'Secure Packaging', bgColor: 'bg-emerald-100', enabled: true, order: 4 },
      { id: 5, iconName: 'Headset', title: '24/7 Support', subtitle: 'We are here for you', bgColor: 'bg-amber-100', actionType: 'support', enabled: true, order: 5 },
    ],
  },
  categorySection: {
    enabled: true,
    title: 'Shop by Category',
    seeAllText: 'See All',
    seeAllUrl: '/products',
  },
  categories: categories,
  popularProducts: {
    enabled: true,
    title: 'Popular Today',
    viewAllText: 'View All',
    viewAllUrl: '/products',
    badgeIcon: '⚡',
    featuredProductIds: ['r1'],
  },
  epicDeals: {
    enabled: true,
    topPillText: 'ZERO GRAVITY SAVINGS',
    mainTitle: 'EPIC DEALS',
    subTitle: 'ALL DAY',
    deals: epicDeals,
  },
  futureArrivals: {
    enabled: true,
    title: 'Future Arrivals',
    subtitle: 'Premium choices coming soon to Farminix',
    items: [
      { id: 1, name: 'Fresh Fruits', image: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 1 },
      { id: 2, name: 'Fresh Vegetables', image: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 2 },
      { id: 3, name: 'Dairy Products', image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 3 },
      { id: 4, name: 'Dry Fruits', image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 4 },
      { id: 5, name: 'Cooking Oils', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 5 },
      { id: 6, name: 'Organic Products', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 6 },
      { id: 7, name: 'Ready-to-Cook Products', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 7 },
    ],
  },
  bottomFeatureStrip: {
    enabled: true,
    boxes: [
      { id: 1, iconName: 'Package', title: 'No Minimum Order', subtitle: 'Order any quantity', bgColor: 'bg-emerald-100', enabled: true, order: 1 },
      { id: 2, iconName: 'RefreshCw', title: 'Easy Returns & Refunds', subtitle: 'Hassle free returns', bgColor: 'bg-emerald-100', enabled: true, order: 2 },
      { id: 3, iconName: 'Headset', title: '24/7 Customer Support', subtitle: 'We are here for you', bgColor: 'bg-amber-100', actionType: 'support', enabled: true, order: 3 },
      { id: 4, iconName: 'ShieldCheck', title: '100% Quality Assured', subtitle: 'Genuine products only', bgColor: 'bg-purple-100', enabled: true, order: 4 },
    ],
  },
  footer: {
    enabled: true,
    logoUrl: '/farminix_logo.png',
    bioText: 'Your trusted partner for quality groceries. Fresh produce, authentic staples, and instant 10-minute home delivery.',
    socialLinks: {
      instagram: 'https://www.instagram.com',
      facebook: 'https://www.facebook.com',
      twitter: 'https://twitter.com',
      youtube: 'https://www.youtube.com',
    },
    companyLinks: [
      { id: 'c1', label: 'About Us', url: '#' },
      { id: 'c2', label: 'Career', url: '#' },
      { id: 'c3', label: 'Blog', url: '#' },
      { id: 'c4', label: 'Contact Us', url: '#', actionType: 'support' },
    ],
    helpLinks: [
      { id: 'h1', label: 'FAQs', url: '#', actionType: 'support' },
      { id: 'h2', label: 'Shipping & Delivery', url: '#' },
      { id: 'h3', label: 'Returns & Refunds', url: '#' },
      { id: 'h4', label: 'Terms & Conditions', url: '#' },
    ],
    downloadApp: {
      googlePlayUrl: '#',
      appleAppStoreUrl: '#',
    },
    legalLinks: [
      { id: 'l1', label: 'Privacy Policy', url: '#' },
      { id: 'l2', label: 'Cancellation Policy', url: '#' },
      { id: 'l3', label: 'Refund Policy', url: '#' },
      { id: 'l4', label: 'Disclaimer', url: '#' },
    ],
    copyrightText: '© 2025 Farminix. All rights reserved.',
  },
  offersPage: {
    enabled: true,
    heroBadge: 'MEGA SAVINGS FESTIVAL',
    heroTitle: 'Zero Gravity Savings',
    heroSubtitle: 'Handpicked grocery deals with guaranteed lowest prices and 10-minute doorstep delivery.',
    countdownHours: 18,
    promoCode: 'FARM10',
  },
  shopNowConfig: {
    enabled: true,
    pageTitle: 'Browse Products',
    minPriceLimit: 100,
    maxPriceLimit: 3000,
    itemsPerPage: 12,
  },
  products: allProducts,
  orders: [
    {
      id: 'ORD-89241',
      date: new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
      items: [{ product: allProducts[0], quantity: 1, selectedWeight: '26 Kg' }],
      totalAmount: 1399,
      discount: 0,
      deliveryFee: 0,
      finalAmount: 1399,
      status: 'Out for Delivery',
      estimatedTime: '15 Mins',
      deliveryAddress: {
        id: 'addr-sample-1',
        name: 'Express Customer',
        street: 'Main Road',
        city: 'Guntur',
        state: 'Andhra Pradesh',
        pincode: '522002',
        phone: '+91 98000 00000',
        isDefault: true,
      },
      paymentMethod: 'UPI',
    },
    {
      id: 'ORD-77412',
      date: '12 Aug 2026',
      items: [{ product: allProducts[0], quantity: 2, selectedWeight: '26 Kg' }],
      totalAmount: 2798,
      discount: 0,
      deliveryFee: 0,
      finalAmount: 2798,
      status: 'Delivered',
      estimatedTime: 'Delivered',
      deliveryAddress: {
        id: 'addr-sample-2',
        name: 'Express Customer',
        street: 'Main Road',
        city: 'Guntur',
        state: 'Andhra Pradesh',
        pincode: '522002',
        phone: '+91 98000 00000',
        isDefault: true,
      },
      paymentMethod: 'CARD',
    },
  ],
  users: [
    {
      id: 'usr-1',
      name: '',
      phone: '',
      email: '',
      rewardPoints: 0,
      walletBalance: 0,
      addresses: [],
    },
  ],
  mediaLibrary: [
    { id: 'med-1', name: 'Farminix Main Logo', url: '/farminix_logo.png', category: 'brand', uploadedAt: '2026-08-10', size: '728 KB' },
    { id: 'med-2', name: 'Hero Banner Image', url: '/hero_banner_original.jpg', category: 'banner', uploadedAt: '2026-08-10', size: '1.9 MB' },
    { id: 'med-3', name: 'Daawat Basmati Rice Pack', url: '/prod_daawat_rice.jpg', category: 'product', uploadedAt: '2026-08-10', size: '522 KB' },
    { id: 'med-4', name: 'Aashirvaad Atta Pack', url: '/prod_aashirvaad_atta.jpg', category: 'product', uploadedAt: '2026-08-10', size: '624 KB' },
    { id: 'med-5', name: 'Fortune Oil Pack', url: '/prod_fortune_oil.jpg', category: 'product', uploadedAt: '2026-08-10', size: '444 KB' },
    { id: 'med-6', name: 'Tata Salt Pack', url: '/prod_tata_salt.jpg', category: 'product', uploadedAt: '2026-08-10', size: '541 KB' },
    { id: 'med-7', name: 'Dals Category Image', url: '/cat_dals.jpg', category: 'category', uploadedAt: '2026-08-10', size: '557 KB' },
    { id: 'med-8', name: 'Rice Category Image', url: '/cat_rice.jpg', category: 'category', uploadedAt: '2026-08-10', size: '495 KB' },
    { id: 'med-9', name: 'Atta Category Image', url: '/cat_atta.jpg', category: 'category', uploadedAt: '2026-08-10', size: '606 KB' },
    { id: 'med-10', name: 'Oils Category Image', url: '/cat_oils.jpg', category: 'category', uploadedAt: '2026-08-10', size: '495 KB' },
    { id: 'med-11', name: 'Masala Category Image', url: '/cat_masala.jpg', category: 'category', uploadedAt: '2026-08-10', size: '595 KB' },
    { id: 'med-12', name: 'Snacks Category Image', url: '/cat_snacks.jpg', category: 'category', uploadedAt: '2026-08-10', size: '573 KB' },
    { id: 'med-13', name: 'Household Category Image', url: '/cat_household.jpg', category: 'category', uploadedAt: '2026-08-10', size: '489 KB' },
    { id: 'med-14', name: 'Sugar & Salt Category Image', url: '/cat_sugar_salt.jpg', category: 'category', uploadedAt: '2026-08-10', size: '514 KB' },
  ],
};
